### ISSUE TITLE
missing region in config

### ISSUE THREAD

**Issue by luiseduardocolon** [rgfindl/headless-wordpress#1]
Not really obvious where to set up the region, since it doesn't use the environment variable AWS_DEFAULT_REGION from the CLI.  So, cim stack-up fails for vpc:

{ ConfigError: Missing region in config
    at Request.VALIDATE_REGION (/usr/local/lib/node_modules/cim/node_modules/aws-sdk/lib/event_listeners.js:92:45)
    at Request.callListeners (/usr/local/lib/node_modules/cim/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at callNextListener (/usr/local/lib/node_modules/cim/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at /usr/local/lib/node_modules/cim/node_modules/aws-sdk/lib/event_listeners.js:86:9
    at finish (/usr/local/lib/node_modules/cim/node_modules/aws-sdk/lib/config.js:341:7)
    at /usr/local/lib/node_modules/cim/node_modules/aws-sdk/lib/config.js:359:9
    at EnvironmentCredentials.get (/usr/local/lib/node_modules/cim/node_modules/aws-sdk/lib/credentials.js:126:7)
    at getAsyncCredentials (/usr/local/lib/node_modules/cim/node_modules/aws-sdk/lib/config.js:353:24)
    at Config.getCredentials (/usr/local/lib/node_modules/cim/node_modules/aws-sdk/lib/config.js:373:9)
    at Request.VALIDATE_CREDENTIALS (/usr/local/lib/node_modules/cim/node_modules/aws-sdk/lib/event_listeners.js:81:26)
  message: 'Missing region in config',
  code: 'ConfigError',
  time: 2018-11-09T01:19:38.868Z }

Thoughts?
Luis

**Comment by dfranc3373** [comment]
Solved by exporting the environment variable as AWS_REGION instead of AWS_DEFAULT_REGION 

 ```export AWS_REGION=us-west-2```
